### ISSUE TITLE
setCookie function works wrong

### ISSUE THREAD

**Issue by nothugofsea** [siberiacancode/mock-config-server#126]
When i pass options to setCookie function, they rewrites by new Set-Cookie header
<img width="774" alt="image" src="https://github.com/siberiacancode/mock-config-server/assets/91194878/166dd2d9-8c30-4367-a627-debca61ae3e3">

for example i wrote this via appendHeader function and it works fine
<img width="617" alt="image" src="https://github.com/siberiacancode/mock-config-server/assets/91194878/14c77722-edeb-4037-b096-6471dcf5d9d7">

**Comment by MiaInturi** [comment]
@nothugofsea Thank you for finding the bug and creating the issue. You can track changes in PR [here](https://github.com/siberiacancode/mock-config-server/pull/127)
