### ISSUE TITLE
Request middleware

### ISSUE THREAD

**Issue by nothugofsea** [siberiacancode/mock-config-server#129]
Hello, recently I've tried to write request interceptor that will check user token and forbid access if token incorrect, but I didn't find the method that will stop further checks and return answer to user with error. I suggest to add middleware field in config object that will be a function which one can stop further checks and return answer to user.

**Comment by debabin** [comment]
Hello, thanks for your feedback, you can complete this task this way

```typescript
const mockServerConfig: MockServerConfig = {
  interceptors: {
    response: (data, { request, setStatusCode }) => {
      const { token } = request.headers;

      if (!token) {
        setStatusCode(401);
        return { success: false };
      }

      return data;
    }
  },
  rest: {
    baseUrl: '/api',
    configs: [
      {
        method: 'post',
        path: '/signin',
...
```

But we must take into account that this interceptor will only work for existing requests, because we need to find a config for this.

**Comment by debabin** [comment]
@nothugofsea another option is to create a server using createMockServer and add middleware to it. This server is a regular express server

```typescript
const mockServerConfig: MockServerConfig = {...}

const server = createMockServer(mockServerConfig);
server.use((req, res, next) => {
  // your logic
  next();
});
```

**Comment by nothugofsea** [comment]
Thank you for answer!
