### ISSUE TITLE
Location of mock-server.config

### ISSUE THREAD

**Issue by soblvsk** [siberiacancode/mock-config-server#141]
Hi, I have such a question:
Is it possible for the `mock-server.config.ts` file to be located not in the root directory, but for example in the api folder, where the api variable will be and the mock with real requests is located in it? (For convenience, for example, comment out one line of the mock and use real queries)

Example:

```
const baseApi = ...
const mockApi = ...

const api = {
  ...baseApi,
  ...mockApi,
};
export {api}
```

And is it possible to split this mock into several files?

**Comment by MiaInturi** [comment]
Hello, @soblvsk. Thanks for using mock-config-server! You can specify path to `mock-server.config.ts` by using `-c` or `--config` flag. 
```bash
$ mcs -c ./api/mock-server.config.ts
```

Also, you can split your mock into different files something like this:
```typescript
import { usersConfig } from './users';
import { settingsConfig } from './settings';

const mockServerConfig = {
  rest: {
    configs: [
      usersConfig,
      settingsConfig 
    ]
  }
};

export default mockServerConfig;
```
but config file can be only one and should have `export default` config object.

**Comment by soblvsk** [comment]
Thanks for the answer! 🔥
