### ISSUE TITLE
Error when importing split configurations

### ISSUE THREAD

**Issue by soblvsk** [siberiacancode/mock-config-server#142]
I get an error and typescript swears when I import other individual configs into the `mock-server.config.ts` file
But if you do not import and immediately write to `mockServerConfig` or delete type `MockServerConfig`, then everything is ok

example:

```ts
const test = {
  method: 'get',
  path: '/products',
  routes: [
    {
      data: { success: true },
    },
  ],
};


const mockServerConfig: MockServerConfig = {
  baseUrl: '/api',
  rest: {
    configs: [test]
   }
  }
```

Error:
```
Type '{ method: string; path: string; routes: { data: { success: boolean; }; }[]; }' is not assignable to type 'RestRequestConfig'.
  Type '{ method: string; path: string; routes: { data: { success: boolean; }; }[]; }' is not assignable to type 'RestOptionsRequestConfig'.
    Types of property 'path' are incompatible.
      Type 'string' is not assignable to type 'RegExp | `/${string}`'
```

> __________________________________________________________________________________________________

I would also like to know: I have such a request:
```ts
getProducts: http.createRoute<{ url: string }, ProductsEntity>({
      url: '/products',
      method: 'GET',
    }),
```
How do I pass `{url:string}` to a function that performs all the filtering by simulating transformations from the backend?I didn't see any examples in the documentation, only embedded ones via `_` or `.`

Now, what I wrote outputs this when I request.url:
`/products?url=%2Fcatalog%3Fpage%3D2`

And logically, you need `/catalog?page=2` or `/products?page=2`

Here's what I wrote:
```js
{
        method: 'get',
        path: '/products',
        routes: [
          {
            data: { success: true },
            interceptors: {
              response: (__, { request }) => {
                const products = catalog.products.filterProducts({
                  url: decodeURIComponent(request.url),
                });

                return products;
              },
            },
          },
        ],
      },
```

**Comment by debabin** [comment]
Hello, @soblvsk. Thanks for using mock-config-server!

Let's consider the first question; currently, the path can only be 'RegExp | /${string}'. In fact, you will encounter a similar error with the method later on. This is because you can solve your issue in the following way:

Use the RestRequestConfig type for your variable.

```ts
const test: RestRequestConfig = {
  method: 'get',
  path: '/products' as RestRequestConfig['path'],
  routes: [
    {
      data: { success: true }
    }
  ]
};
```
or
```ts
const test = {
  method: 'get',
  path: '/products' as RestRequestConfig['path'],
  routes: [
    {
      data: { success: true }
    }
  ]
} satisfies RestRequestConfig;
```

In the second case, you can retrieve the URL from the request.query parameters. [Request ](https://expressjs.com/ru/api.html#req)is express object

```ts
{
  data: { success: true },
  interceptors: {
    response: (__, { request }) => {
      const { query } = request;
      const products = catalog.products.filterProducts({
        url: query.url
      });

      return products;
    }
  }
}
```

**Comment by soblvsk** [comment]
Thanks !

**Comment by debabin** [comment]
If you @soblvsk have any wishes to work with config requests, we would like to hear them. Thanks again for using our library.
