### ISSUE TITLE
Config BaseURL

### ISSUE THREAD

**Issue by soblvsk** [siberiacancode/mock-config-server#161]
When running mock-config-server. The baseUrl (/api) has stopped being taken into account. What could be the problem?

```
mock-config-server: 3.4.0
node: 18.18.0
pnpm: 8.15.5
```

```
$ pnpm --filter @onlineclothingshop/client run mock
> npx mock-config-server -c ./src/shared/api/mocks/mock-server.config.ts -w
```

![image](https://github.com/siberiacancode/mock-config-server/assets/81454805/d12b1f6b-d662-4936-a92b-2af8320c9f78)

**Comment by MiaInturi** [comment]
@soblvsk Hi, it is a bug started from version 3.4.0. We will fix it soon.

**Comment by MiaInturi** [comment]
@soblvsk release 3.4.1 is available now. Bug fixed. Thanks for report this issue

**Comment by soblvsk** [comment]
@MiaInturi It was updated and for some reason it still doesn't work

![image](https://github.com/siberiacancode/mock-config-server/assets/81454805/3eaf1964-fc26-4022-883e-62cf16da8792)
