### ISSUE TITLE
It crashes when you combine pagination and sorting

### ISSUE THREAD

**Issue by stasguma** [siberiacancode/mock-config-server#173]
![image](https://github.com/siberiacancode/mock-config-server/assets/15160733/90ce62f4-3d19-4e3e-afc0-474d5ec9ca63)

It seems that you just need to move the sorting above the pagination here [createNestedDatabaseRoutes.ts](https://github.com/siberiacancode/mock-config-server/blob/main/src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts#L43), but I'm not sure.

**Comment by debabin** [comment]
Hello, thanks for using our library, we found and fixed the problem, sent it for review
