### ISSUE TITLE
Filter returns nothing if value is an array

### ISSUE THREAD

**Issue by stasguma** [siberiacancode/mock-config-server#178]
There is a property in my db.json that is an array, when I try to filter like `...articles?categories=music`, it returns nothing.
I don't know if it is a bug. Is there any way to do it?

`{
   categories: ['music', 'movie', 'sport']
}`

**Comment by debabin** [comment]
Hello, thanks for using our library, we are considering the option of adding new methods for filter, such as some and every for an array, and we will also show an option on how to implement more complex interaction through an interceptor

![image](https://github.com/siberiacancode/mock-config-server/assets/45297354/2f3eb78c-1457-48c4-8385-bf90adebfbb4)
