### ISSUE TITLE
Helpers functions for response interceptors: cache and cookie

### ISSUE THREAD

**Issue by MiaInturi** [siberiacancode/mock-config-server#26]
Need to add into response interceptors new setters: for 'Cache-Control' and 'Set-Cookie' http headers

**Comment by MiaInturi** [comment]
#### Why 'Cache-Control' http header will be useless for our server which based on Express?
Express has builtin [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) support, so browser (modern at least) automatically save response body in cache. If response body will change then ETag change too and browser update cache.
![etag](https://user-images.githubusercontent.com/39031929/226108088-0c483bb6-5ace-4267-a9e6-d677e6dad82f.png)

**Comment by debabin** [comment]
What if the user wants to disable the Etag? And what about another setters, do we have any special unfinished setters ?

**Comment by MiaInturi** [comment]
If user disables Etag then caching just turn off and nothing more happens. In my commit i set 'Cache-Control' header for avoid [heuristic caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching) that depends on browser implementation
